[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http.tls]
    certResolver = "letsencrypt"

[api]
  dashboard = true

[certificatesResolvers.letsencrypt.acme]
  email = "domains@leviscop.net"
  storage = "acme-dns.json"
  [certificatesResolvers.letsencrypt.acme.dnsChallenge]
    provider = "cloudns"
    delayBeforeCheck = 30  
    resolvers = ["1.1.1.1", "8.8.8.8", "2606:4700:4700::1111", "2001:4860:4860::8888"]

[certificatesResolvers.letsencrypt-tls.acme]
  email = "domains@leviscop.net"
  storage = "acme-tls.json"
  [certificatesResolvers.letsencrypt-tls.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "gateway"
  exposedByDefault = false

[log]
  level = "DEBUG"
